<?php

return [
    'views' => [
        'builder' => 'generator-builder::builder',
        'field-template' => 'generator-builder::field-template',
        'field-detail-template' => 'generator-builder::field-detail-template',
        'relation-field-template' => 'generator-builder::relation-field-template',
    ],
    'txtDbType' => ['Increments', 'integer', 'smallInteger', 'longText', 'bigInteger', 'double', 'float', 'decimal', 'boolean', 'string', 'char', 'text', 'mediumText', 'longText', 'enum', 'binary', 'dateTime', 'date', 'timestamp'],
    'htmlType' => ['text', 'email', 'number', 'date', 'file', 'image', 'password', 'select', 'radio', 'checkbox', 'textarea', 'toggle-switch'],
    'commandType' => ['yusuftogtay:api_scaffold', 'yusuftogtay:api', 'yusuftogtay:scaffold'],
    /**
     ********************************
     * Rules
     * ******************************.
     *
     * name: rule name
     * title: rule title
     * description: rule description
     * descriptionHtml: rule description html
     * link: rule link
     * htmlType: html input type
     * dbType: database type
     * validation: validation rule
     */
    'ruleType' => [
        'accepted' => [
            'name' => 'Accepted',
            'title' => 'accepted',
            'description' => 'The field under validation must be yes, on, 1, or true. This is useful for validating "Terms of Service" acceptance.',
            'descriptionHtml' => '<p>The field under validation must be <code>"yes"</code>, <code>"on"</code>, <code>1</code>, or <code>true</code>. This is useful for validating "Terms of Service" acceptance or similar fields.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-accepted',
            'htmlType' => ['checkbox'],
            'dbType' => ['boolean'],
            'validation' => ['accepted'],
        ],
        'active_url' => [
            'name' => 'ActiveUrl',
            'title' => 'active_url',
            'description' => 'The field under validation must have a valid A or AAAA record according to the dns_get_record PHP function.',
            'descriptionHtml' => '<p>The field under validation must have a valid A or AAAA record according to the <code>dns_get_record</code> PHP function.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-active-url',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['active_url'],
        ],
        'after' => [
            'name' => 'After',
            'title' => 'after',
            'description' => 'The field under validation must be a value after a given date.',
            'descriptionHtml' => '<p>The field under validation must be a value after a given <code>date</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-after',
            'htmlType' => ['date'],
            'dbType' => ['dateTime', 'date'],
            'validation' => ['after:'],
        ],
        'after_or_equal' => [
            'name' => 'AfterOrEqual',
            'title' => 'after_or_equal',
            'description' => 'The field under validation must be a value after or equal to the given date.',
            'descriptionHtml' => '<p>The field under validation must be a value after or equal to the given <code>date</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-after-or-equal',
            'htmlType' => ['date'],
            'dbType' => ['dateTime', 'date'],
            'validation' => ['after_or_equal:'],
        ],
        'alpha' => [
            'name' => 'Alpha',
            'title' => 'alpha',
            'description' => 'The field under validation must be entirely alphabetic characters.',
            'descriptionHtml' => '<p>The field under validation must be entirely alphabetic characters.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-alpha',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['alpha'],
        ],
        'alpha_dash' => [
            'name' => 'AlphaDash',
            'title' => 'alpha_dash',
            'description' => 'The field under validation may have alpha-numeric characters, as well as dashes and underscores.',
            'descriptionHtml' => '<p>The field under validation may have alpha-numeric characters, as well as dashes and underscores.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-alpha-dash',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['alpha_dash'],
        ],
        'alpha_num' => [
            'name' => 'AlphaNum',
            'title' => 'alpha_num',
            'description' => 'The field under validation must be entirely alpha-numeric characters.',
            'descriptionHtml' => '<p>The field under validation must be entirely alpha-numeric characters.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-alpha-num',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['alpha_num'],
        ],
        'array' => [
            'name' => 'Array',
            'title' => 'array',
            'description' => 'The field under validation must be a PHP array.',
            'descriptionHtml' => '<p>The field under validation must be a PHP array.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-array',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['array'],
        ],
        'ascii' => [
            'name' => 'Ascii',
            'title' => 'ascii',
            'description' => 'The field under validation must only contain ASCII characters.',
            'descriptionHtml' => '<p>The field under validation must only contain ASCII characters.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-ascii',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['ascii'],
        ],
        'bail' => [
            'name' => 'Bail',
            'title' => 'bail',
            'description' => 'Stop running validation rules after the first validation failure.',
            'descriptionHtml' => '<p>Stop running validation rules after the first validation failure.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-bail',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['bail'],
        ],
        'before' => [
            'name' => 'Before',
            'title' => 'before',
            'description' => 'The field under validation must be a value preceding the given date.',
            'descriptionHtml' => '<p>The field under validation must be a value preceding the given <code>date</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-before',
            'htmlType' => ['date'],
            'dbType' => ['dateTime', 'date'],
            'validation' => ['before:'],
        ],
        'before_or_equal' => [
            'name' => 'BeforeOrEqual',
            'title' => 'before_or_equal',
            'description' => 'The field under validation must be a value preceding or equal to the given date.',
            'descriptionHtml' => '<p>The field under validation must be a value preceding or equal to the given <code>date</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-before-or-equal',
            'htmlType' => ['date'],
            'dbType' => ['dateTime', 'date'],
            'validation' => ['before_or_equal:'],
        ],
        'between' => [
            'name' => 'Between',
            'title' => 'between',
            'description' => 'The field under validation must have a size between the given min and max.',
            'descriptionHtml' => '<p>The field under validation must have a size between the given <code>min</code> and <code>max</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-between',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['between:'],
        ],
        'boolean' => [
            'name' => 'Boolean',
            'title' => 'boolean',
            'description' => 'The field under validation must be able to be cast as a boolean. Accepted input are true, false, 1, 0, "1", and "0".',
            'descriptionHtml' => '<p>The field under validation must be able to be cast as a boolean. Accepted input are <code>true</code>, <code>false</code>, <code>1</code>, <code>0</code>, <code>"1"</code>, and <code>"0"</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-boolean',
            'htmlType' => ['checkbox'],
            'dbType' => ['boolean'],
            'validation' => ['boolean'],
        ],
        'confirmed' => [
            'name' => 'Confirmed',
            'title' => 'confirmed',
            'description' => 'The field under validation must have a matching field of foo_confirmation. For example, if the field under validation is password, a matching password_confirmation field must be present in the input.',
            'descriptionHtml' => '<p>The field under validation must have a matching field of <code>foo_confirmation</code>. For example, if the field under validation is <code>password</code>, a matching <code>password_confirmation</code> field must be present in the input.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-confirmed',
            'htmlType' => ['password'],
            'dbType' => ['string'],
            'validation' => ['confirmed'],
        ],
        'current_password' => [
            'name' => 'CurrentPassword',
            'title' => 'current_password',
            'description' => 'The field under validation must match the authenticated user\'s password.',
            'descriptionHtml' => '<p>The field under validation must match the authenticated user\'s password.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-current-password',
            'htmlType' => ['password'],
            'dbType' => ['string'],
            'validation' => ['current_password'],
        ],
        'date' => [
            'name' => 'Date',
            'title' => 'date',
            'description' => 'The field under validation must be a valid date according to the strtotime PHP function.',
            'descriptionHtml' => '<p>The field under validation must be a valid date according to the <code>strtotime</code> PHP function.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-date',
            'htmlType' => ['date'],
            'dbType' => ['dateTime', 'date'],
            'validation' => ['date'],
        ],
        'date_equals' => [
            'name' => 'DateEquals',
            'title' => 'date_equals',
            'description' => 'The field under validation must be equal to the given date.',
            'descriptionHtml' => '<p>The field under validation must be equal to the given <code>date</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-date-equals',
            'htmlType' => ['date'],
            'dbType' => ['dateTime', 'date'],
            'validation' => ['date_equals:'],
        ],
        'date_format' => [
            'name' => 'DateFormat',
            'title' => 'date_format',
            'description' => 'The field under validation must match the given format.',
            'descriptionHtml' => '<p>The field under validation must match the given <code>format</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-date-format',
            'htmlType' => ['date'],
            'dbType' => ['dateTime', 'date'],
            'validation' => ['date_format:'],
        ],
        'decimal' => [
            'name' => 'Decimal',
            'title' => 'decimal',
            'description' => 'The field under validation must be a decimal.',
            'descriptionHtml' => '<p>The field under validation must be a decimal.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-decimal',
            'htmlType' => ['number'],
            'dbType' => ['decimal'],
            'validation' => ['decimal:'],
        ],
        'declined' => [
            'name' => 'Declined',
            'title' => 'declined',
            'description' => 'The field under validation must be no, off, 0, or false.',
            'descriptionHtml' => '<p>The field under validation must be <code>"no"</code>, <code>"off"</code>, <code>0</code>, or <code>false</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-declined',
            'htmlType' => ['checkbox'],
            'dbType' => ['boolean'],
            'validation' => ['declined'],
        ],
        'declined_if' => [
            'name' => 'Declined If',
            'title' => 'declined_if',
            'description' => 'The field under validation must be no, off, 0, or false if anotherfield equals any value.',
            'descriptionHtml' => '<p>The field under validation must be <code>"no"</code>, <code>"off"</code>, <code>0</code>, or <code>false</code> if <code>anotherfield</code> equals any value.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-declined-if',
            'htmlType' => ['checkbox'],
            'dbType' => ['boolean'],
            'validation' => ['declined_if:'],
        ],
        'different' => [
            'name' => 'Different',
            'title' => 'different',
            'description' => 'The field under validation must have a different value than field.',
            'descriptionHtml' => '<p>The field under validation must have a different value than <code>field</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-different',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['different:'],
        ],
        'digits' => [
            'name' => 'Digits',
            'title' => 'digits',
            'description' => 'The field under validation must be numeric and must have an exact length of value.',
            'descriptionHtml' => '<p>The field under validation must be numeric and must have an exact length of <code>value</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-digits',
            'htmlType' => ['number'],
            'dbType' => ['integer'],
            'validation' => ['digits:'],
        ],
        'digits_between' => [
            'name' => 'DigitsBetween',
            'title' => 'digits_between',
            'description' => 'The field under validation must have a length between the given min and max.',
            'descriptionHtml' => '<p>The field under validation must have a length between the given <code>min</code> and <code>max</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-digits-between',
            'htmlType' => ['number'],
            'dbType' => ['integer'],
            'validation' => ['digits_between:'],
        ],
        'dimensions' => [
            'name' => 'Dimensions',
            'title' => 'dimensions',
            'description' => 'The file under validation must be an image meeting the dimension constraints as specified by the rule\'s parameters.',
            'descriptionHtml' => '<p>The file under validation must be an image meeting the dimension constraints as specified by the rule\'s parameters.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-dimensions',
            'htmlType' => ['file', 'image'],
            'dbType' => ['string'],
            'validation' => ['dimensions:'],
        ],
        'distinct' => [
            'name' => 'Distinct',
            'title' => 'distinct',
            'description' => 'The field under validation must be unique among all of the other values of field.',
            'descriptionHtml' => '<p>The field under validation must be unique among all of the other values of <code>field</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-distinct',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['distinct'],
        ],
        'dosent_start_with' => [
            'name' => 'Dosent Start With',
            'title' => 'dosent_start_with',
            'description' => 'The field under validation must not start with one of the given values.',
            'descriptionHtml' => '<p>The field under validation must not start with one of the given values.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-dosent-start-with',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['dosent_start_with:'],
        ],
        'dosent_end_with' => [
            'name' => 'Dosent End With',
            'title' => 'dosent_end_with',
            'description' => 'The field under validation must not end with one of the given values.',
            'descriptionHtml' => '<p>The field under validation must not end with one of the given values.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-dosent-end-with',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['dosent_end_with:'],
        ],
        'email' => [
            'name' => 'Email',
            'title' => 'email',
            'description' => 'The field under validation must be formatted as an e-mail address.',
            'descriptionHtml' => '<p>The field under validation must be formatted as an e-mail address.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-email',
            'htmlType' => ['email'],
            'dbType' => ['string'],
            'validation' => ['email'],
        ],
        'ends_with' => [
            'name' => 'EndsWith',
            'title' => 'ends_with',
            'description' => 'The field under validation must end with one of the given values.',
            'descriptionHtml' => '<p>The field under validation must end with one of the given values.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-ends-with',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['ends_with:'],
        ],
        'enum' => [
            'name' => 'Enum',
            'title' => 'enum',
            'description' => 'The field under validation must be included in the given list of enum values.',
            'descriptionHtml' => '<p>The field under validation must be included in the given list of enum values.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-enum',
            'htmlType' => ['select'],
            'dbType' => ['enum'],
            'validation' => ['enum:'],
        ],
        'exclude_if' => [
            'name' => 'ExcludeIf',
            'title' => 'exclude_if',
            'description' => 'The field under validation must be present only if the anotherfield field is equal to any value.',
            'descriptionHtml' => '<p>The field under validation must be present only if the <code>anotherfield</code> field is equal to any value.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-exclude-if',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['exclude_if:'],
        ],
        'exclude_unless' => [
            'name' => 'ExcludeUnless',
            'title' => 'exclude_unless',
            'description' => 'The field under validation must be present only when the anotherfield field is equal to any value.',
            'descriptionHtml' => '<p>The field under validation must be present only when the <code>anotherfield</code> field is equal to any value.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-exclude-unless',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['exclude_unless:'],
        ],
        'exclude' => [
            'name' => 'Exclude',
            'title' => 'exclude',
            'description' => 'The field under validation must not be included in the given list of values.',
            'descriptionHtml' => '<p>The field under validation must not be included in the given list of values.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-exclude',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['exclude:'],
        ],
        'exclude_without' => [
            'name' => 'ExcludeWithout',
            'title' => 'exclude_without',
            'description' => 'The field under validation must be present only when any of the other specified fields are present.',
            'descriptionHtml' => '<p>The field under validation must be present only when any of the other specified fields are present.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-exclude-without',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['exclude_without:'],
        ],
        'exists' => [
            'name' => 'Exists',
            'title' => 'exists',
            'description' => 'The field under validation must exist on a given database table.',
            'descriptionHtml' => '<p>The field under validation must exist on a given database <code>table</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-exists',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['exists:'],
        ],
        'file' => [
            'name' => 'File',
            'title' => 'file',
            'description' => 'The field under validation must be a successfully uploaded file.',
            'descriptionHtml' => '<p>The field under validation must be a successfully uploaded file.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-file',
            'htmlType' => ['file'],
            'dbType' => ['string'],
            'validation' => ['file'],
        ],
        'filled' => [
            'name' => 'Filled',
            'title' => 'filled',
            'description' => 'The field under validation must not be empty when it is present.',
            'descriptionHtml' => '<p>The field under validation must not be empty when it is present.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-filled',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['filled'],
        ],
        'gt' => [
            'name' => 'GreaterThan',
            'title' => 'gt',
            'description' => 'The field under validation must be greater than the given field.',
            'descriptionHtml' => '<p>The field under validation must be greater than the given <code>field</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-gt',
            'htmlType' => ['number'],
            'dbType' => ['integer'],
            'validation' => ['gt:'],
        ],
        'gte' => [
            'name' => 'GreaterThanOrEqual',
            'title' => 'gte',
            'description' => 'The field under validation must be greater than or equal to the given field.',
            'descriptionHtml' => '<p>The field under validation must be greater than or equal to the given <code>field</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-gte',
            'htmlType' => ['number'],
            'dbType' => ['integer'],
            'validation' => ['gte:'],
        ],
        'image' => [
            'name' => 'Image',
            'title' => 'image',
            'description' => 'The file under validation must be an image (jpeg, png, bmp, gif, svg, or webp)',
            'descriptionHtml' => '<p>The file under validation must be an image (jpeg, png, bmp, gif, svg, or webp)</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-image',
            'htmlType' => ['image'],
            'dbType' => ['string'],
            'validation' => ['image'],
        ],
        'in' => [
            'name' => 'In',
            'title' => 'in',
            'description' => 'The field under validation must be included in the given list of values.',
            'descriptionHtml' => '<p>The field under validation must be included in the given list of values.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-in',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['in:'],
        ],
        'in_array' => [
            'name' => 'InArray',
            'title' => 'in_array',
            'description' => 'The field under validation must exist in anotherfield\'s values.',
            'descriptionHtml' => '<p>The field under validation must exist in <code>anotherfield</code>\'s values.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-in-array',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['in_array:'],
        ],
        'integer' => [
            'name' => 'Integer',
            'title' => 'integer',
            'description' => 'The field under validation must be an integer.',
            'descriptionHtml' => '<p>The field under validation must be an integer.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-integer',
            'htmlType' => ['number'],
            'dbType' => ['integer'],
            'validation' => ['integer'],
        ],
        'ip' => [
            'name' => 'Ip',
            'title' => 'ip',
            'description' => 'The field under validation must be an IP address.',
            'descriptionHtml' => '<p>The field under validation must be an IP address.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-ip',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['ip'],
        ],
        'ipv4' => [
            'name' => 'Ipv4',
            'title' => 'ipv4',
            'description' => 'The field under validation must be an IPv4 address.',
            'descriptionHtml' => '<p>The field under validation must be an IPv4 address.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-ipv4',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['ipv4'],
        ],
        'ipv6' => [
            'name' => 'Ipv6',
            'title' => 'ipv6',
            'description' => 'The field under validation must be an IPv6 address.',
            'descriptionHtml' => '<p>The field under validation must be an IPv6 address.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-ipv6',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['ipv6'],
        ],
        'json' => [
            'name' => 'Json',
            'title' => 'json',
            'description' => 'The field under validation must be a valid JSON string.',
            'descriptionHtml' => '<p>The field under validation must be a valid JSON string.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-json',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['json'],
        ],
        'lt' => [
            'name' => 'LessThan',
            'title' => 'lt',
            'description' => 'The field under validation must be less than the given field.',
            'descriptionHtml' => '<p>The field under validation must be less than the given <code>field</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-lt',
            'htmlType' => ['number'],
            'dbType' => ['integer'],
            'validation' => ['lt:'],
        ],
        'lte' => [
            'name' => 'LessThanOrEqual',
            'title' => 'lte',
            'description' => 'The field under validation must be less than or equal to the given field.',
            'descriptionHtml' => '<p>The field under validation must be less than or equal to the given <code>field</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-lte',
            'htmlType' => ['number'],
            'dbType' => ['integer'],
            'validation' => ['lte:'],
        ],
        'max' => [
            'name' => 'Max',
            'title' => 'max',
            'description' => 'The field under validation must be less than or equal to a maximum value. Strings, numerics, arrays, and files are evaluated in the same fashion as the size rule.',
            'descriptionHtml' => '<p>The field under validation must be less than or equal to a maximum <code>value</code>. Strings, numerics, arrays, and files are evaluated in the same fashion as the <code>size</code> rule.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-max',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['max:'],
        ],
        'lowercase' => [
            'name' => 'Lowercase',
            'title' => 'lowercase',
            'description' => 'The field under validation must be entirely lowercase.',
            'descriptionHtml' => '<p>The field under validation must be entirely lowercase.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-lowercase',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['lowercase'],
        ],
        'mac_address' => [
            'name' => 'MacAddress',
            'title' => 'mac_address',
            'description' => 'The field under validation must be a valid MAC address.',
            'descriptionHtml' => '<p>The field under validation must be a valid MAC address.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-mac-address',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['mac_address'],
        ],
        'mime_types' => [
            'name' => 'Mime types',
            'title' => 'mime_types',
            'description' => 'The file under validation must match one of the given MIME types.',
            'descriptionHtml' => '<p>The file under validation must match one of the given MIME types.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-mimetypes',
            'htmlType' => ['file'],
            'dbType' => ['string'],
            'validation' => ['mimetypes:'],
        ],
        'mime_types_by_extension' => [
            'name' => 'MimetypesByExtension',
            'title' => 'mime_types_by_extension',
            'description' => 'The file under validation must have a MIME type corresponding to one of the listed extensions.',
            'descriptionHtml' => '<p>The file under validation must have a MIME type corresponding to one of the listed extensions.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-mimetypes-by-extensions',
            'htmlType' => ['file'],
            'dbType' => ['string'],
            'validation' => ['mimetypes:'],
        ],
        'min' => [
            'name' => 'Min',
            'title' => 'min',
            'description' => 'The field under validation must have a minimum value. Strings, numerics, arrays, and files are evaluated in the same fashion as the size rule.',
            'descriptionHtml' => '<p>The field under validation must have a minimum <code>value</code>. Strings, numerics, arrays, and files are evaluated in the same fashion as the <code>size</code> rule.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-min',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['min:'],
        ],
        'min_digit' => [
            'name' => 'Min Digit',
            'title' => 'min_digit',
            'description' => 'The field under validation must have a minimum number of digits.',
            'descriptionHtml' => '<p>The field under validation must have a minimum number of digits.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-min-digit',
            'htmlType' => ['number'],
            'dbType' => ['integer'],
            'validation' => ['min:'],
        ],
        'missing' => [
            'name' => 'Missing',
            'title' => 'missing',
            'description' => 'The field under validation must be missing from the input data.',
            'descriptionHtml' => '<p>The field under validation must be missing from the input data.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-missing',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['missing'],
        ],
        'missing_if' => [
            'name' => 'Missing If',
            'title' => 'missing_if',
            'description' => 'The field under validation must be missing from the input data when anotherfield equals any value.',
            'descriptionHtml' => '<p>The field under validation must be missing from the input data when <code>anotherfield</code> equals any value.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-missing-if',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['missing_if:'],
        ],
        'missing_unless' => [
            'name' => 'Missing Unless',
            'title' => 'missing_unless',
            'description' => 'The field under validation must be missing from the input data when anotherfield equals any value.',
            'descriptionHtml' => '<p>The field under validation must be missing from the input data when <code>anotherfield</code> equals any value.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-missing-unless',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['missing_unless:'],
        ],
        'missing_with' => [
            'name' => 'Missing With',
            'title' => 'missing_with',
            'description' => 'The field under validation must be missing from the input data when any of the other specified fields are present.',
            'descriptionHtml' => '<p>The field under validation must be missing from the input data when any of the other specified fields are present.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-missing-with',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['missing_with:'],
        ],
        'missing_with_all' => [
            'name' => 'Missing With All',
            'title' => 'missing_with_all',
            'description' => 'The field under validation must be missing from the input data when all of the other specified fields are present.',
            'descriptionHtml' => '<p>The field under validation must be missing from the input data when all of the other specified fields are present.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-missing-with-all',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['missing_with_all:'],
        ],
        'multiple_of' => [
            'name' => 'Multiple Of',
            'title' => 'multiple_of',
            'description' => 'The field under validation must be a multiple of value.',
            'descriptionHtml' => '<p>The field under validation must be a multiple of <code>value</code>.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-multiple-of',
            'htmlType' => ['number'],
            'dbType' => ['integer'],
            'validation' => ['multiple_of:'],
        ],
        'not_in' => [
            'name' => 'Not In',
            'title' => 'not_in',
            'description' => 'The field under validation must not be included in the given list of values.',
            'descriptionHtml' => '<p>The field under validation must not be included in the given list of values.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-not-in',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['not_in:'],
        ],
        'not_regex' => [
            'name' => 'Not Regex',
            'title' => 'not_regex',
            'description' => 'The field under validation must not match the given regular expression.',
            'descriptionHtml' => '<p>The field under validation must not match the given regular expression.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-not-regex',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['not_regex:'],
        ],
        'nullable' => [
            'name' => 'Nullable',
            'title' => 'nullable',
            'description' => 'The field under validation may be null.',
            'descriptionHtml' => '<p>The field under validation may be null.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-nullable',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['nullable'],
        ],
        'numeric' => [
            'name' => 'Numeric',
            'title' => 'numeric',
            'description' => 'The field under validation must be numeric.',
            'descriptionHtml' => '<p>The field under validation must be numeric.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-numeric',
            'htmlType' => ['number'],
            'dbType' => ['integer'],
            'validation' => ['numeric'],
        ],
        'password' => [
            'name' => 'Password',
            'title' => 'password',
            'description' => 'The field under validation must match the authenticated user\'s password.',
            'descriptionHtml' => '<p>The field under validation must match the authenticated user\'s password.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-password',
            'htmlType' => ['password'],
            'dbType' => ['string'],
            'validation' => ['password'],
        ],
        'present' => [
            'name' => 'Present',
            'title' => 'present',
            'description' => 'The field under validation must be present in the input data but can be empty.',
            'descriptionHtml' => '<p>The field under validation must be present in the input data but can be empty.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-present',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['present'],
        ],
        'prohibited' => [
            'name' => 'Prohibited',
            'title' => 'prohibited',
            'description' => 'The field under validation must be present in the input data but must be empty.',
            'descriptionHtml' => '<p>The field under validation must be present in the input data but must be empty.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-prohibited',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['prohibited'],
        ],
        'prohibited_if' => [
            'name' => 'Prohibited If',
            'title' => 'prohibited_if',
            'description' => 'The field under validation must be present and not empty if the anotherfield field is equal to any value.',
            'descriptionHtml' => '<p>The field under validation must be present and not empty if the <code>anotherfield</code> field is equal to any value.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-prohibited-if',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['prohibited_if:'],
        ],
        'prohibited_unless' => [
            'name' => 'Prohibited Unless',
            'title' => 'prohibited_unless',
            'description' => 'The field under validation must be present and not empty unless the anotherfield field is equal to any value.',
            'descriptionHtml' => '<p>The field under validation must be present and not empty unless the <code>anotherfield</code> field is equal to any value.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-prohibited-unless',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['prohibited_unless:'],
        ],
        'prohibits' => [
            'name' => 'Prohibits',
            'title' => 'prohibits',
            'description' => 'The field under validation must not be present in the input data.',
            'descriptionHtml' => '<p>The field under validation must not be present in the input data.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-prohibits',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['prohibits:'],
        ],
        'regex' => [
            'name' => 'Regex',
            'title' => 'regex',
            'description' => 'The field under validation must match the given regular expression.',
            'descriptionHtml' => '<p>The field under validation must match the given regular expression.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-regex',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['regex:'],
        ],
        'required' => [
            'name' => 'Required',
            'title' => 'required',
            'description' => 'The field under validation must be present in the input data and not empty.',
            'descriptionHtml' => '<p>The field under validation must be present in the input data and not empty.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-required',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['required'],
        ],
        'required_if' => [
            'name' => 'Required If',
            'title' => 'required_if',
            'description' => 'The field under validation must be present and not empty if the anotherfield field is equal to any value.',
            'descriptionHtml' => '<p>The field under validation must be present and not empty if the <code>anotherfield</code> field is equal to any value.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-required-if',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['required_if:'],
        ],
        'required_unless' => [
            'name' => 'Required Unless',
            'title' => 'required_unless',
            'description' => 'The field under validation must be present and not empty unless the anotherfield field is equal to any value.',
            'descriptionHtml' => '<p>The field under validation must be present and not empty unless the <code>anotherfield</code> field is equal to any value.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-required-unless',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['required_unless:'],
        ],
        'required_with' => [
            'name' => 'Required With',
            'title' => 'required_with',
            'description' => 'The field under validation must be present and not empty only if any of the other specified fields are present.',
            'descriptionHtml' => '<p>The field under validation must be present and not empty only if any of the other specified fields are present.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-required-with',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['required_with:'],
        ],
        'required_with_all' => [
            'name' => 'Required With All',
            'title' => 'required_with_all',
            'description' => 'The field under validation must be present and not empty only if all of the other specified fields are present.',
            'descriptionHtml' => '<p>The field under validation must be present and not empty only if all of the other specified fields are present.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-required-with-all',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['required_with_all:'],
        ],
        'required_without' => [
            'name' => 'Required Without',
            'title' => 'required_without',
            'description' => 'The field under validation must be present and not empty only when any of the other specified fields are not present.',
            'descriptionHtml' => '<p>The field under validation must be present and not empty only when any of the other specified fields are not present.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-required-without',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['required_without:'],
        ],
        'required_without_all' => [
            'name' => 'Required Without All',
            'title' => 'required_without_all',
            'description' => 'The field under validation must be present and not empty only when all of the other specified fields are not present.',
            'descriptionHtml' => '<p>The field under validation must be present and not empty only when all of the other specified fields are not present.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-required-without-all',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['required_without_all:'],
        ],
        'required_array_keys' => [
            'name' => 'Required Array Keys',
            'title' => 'required_array_keys',
            'description' => 'The field under validation must contain all of the given keys.',
            'descriptionHtml' => '<p>The field under validation must contain all of the given keys.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-required-array-keys',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['required_array_keys:'],
        ],
        'same' => [
            'name' => 'Same',
            'title' => 'same',
            'description' => 'The given field must match the field under validation.',
            'descriptionHtml' => '<p>The given field must match the field under validation.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-same',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['same:'],
        ],
        'size' => [
            'name' => 'Size',
            'title' => 'size',
            'description' => 'The field under validation must have a size matching the given value. For string data, value corresponds to the number of characters. For numeric data, value corresponds to a given integer value (the attribute must also have the numeric or integer rule). For an array, size corresponds to the count of the array. For files, size corresponds to the file size in kilobytes.',
            'descriptionHtml' => '<p>The field under validation must have a size matching the given <code>value</code>. For string data, <code>value</code> corresponds to the number of characters. For numeric data, <code>value</code> corresponds to a given integer value (the attribute must also have the <code>numeric</code> or <code>integer</code> rule). For an array, <code>size</code> corresponds to the count of the array. For files, <code>size</code> corresponds to the file size in kilobytes.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-size',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['size:'],
        ],
        'sometimes' => [
            'name' => 'Sometimes',
            'title' => 'sometimes',
            'description' => 'The field under validation must be present in the input data but can be empty.',
            'descriptionHtml' => '<p>The field under validation must be present in the input data but can be empty.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-sometimes',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['sometimes'],
        ],
        'starts_with' => [
            'name' => 'StartsWith',
            'title' => 'starts_with',
            'description' => 'The field under validation must start with one of the given values.',
            'descriptionHtml' => '<p>The field under validation must start with one of the given values.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-starts-with',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['starts_with:'],
        ],
        'string' => [
            'name' => 'String',
            'title' => 'string',
            'description' => 'The field under validation must be a string.',
            'descriptionHtml' => '<p>The field under validation must be a string.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-string',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['string'],
        ],
        'timezone' => [
            'name' => 'Timezone',
            'title' => 'timezone',
            'description' => 'The field under validation must be a valid timezone identifier according to the <a href="https://www.php.net/manual/en/timezones.php">timezone_identifiers_list</a> PHP function.',
            'descriptionHtml' => '<p>The field under validation must be a valid timezone identifier according to the <a href="https://www.php.net/manual/en/timezones.php">timezone_identifiers_list</a> PHP function.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-timezone',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['timezone'],
        ],
        'unique' => [
            'name' => 'Unique',
            'title' => 'unique',
            'description' => 'The field under validation must be unique on a given database table. If the column option is not specified, the field name will be used.',
            'descriptionHtml' => '<p>The field under validation must be unique on a given database table. If the <code>column</code> option is not specified, the field name will be used.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-unique',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['unique:'],
        ],
        'uppercase' => [
            'name' => 'Upper case',
            'title' => 'uppercase',
            'description' => 'The field under validation must be entirely uppercase.',
            'descriptionHtml' => '<p>The field under validation must be entirely uppercase.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-uppercase',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['uppercase'],
        ],
        'url' => [
            'name' => 'Url',
            'title' => 'url',
            'description' => 'The field under validation must be a valid URL.',
            'descriptionHtml' => '<p>The field under validation must be a valid URL.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-url',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['url'],
        ],
        'ulid' => [
            'name' => 'Ulid',
            'title' => 'ulid',
            'description' => 'The field under validation must be a valid ULID.',
            'descriptionHtml' => '<p>The field under validation must be a valid ULID.</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-ulid',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['ulid'],
        ],
        'uuid' => [
            'name' => 'Uuid',
            'title' => 'uuid',
            'description' => 'The field under validation must be a valid RFC 4122 (version 1, 3, 4, or 5) universally unique identifier (UUID).',
            'descriptionHtml' => '<p>The field under validation must be a valid RFC 4122 (version 1, 3, 4, or 5) universally unique identifier (UUID).</p>',
            'link' => 'https://laravel.com/docs/10.x/validation#rule-uuid',
            'htmlType' => ['text'],
            'dbType' => ['string'],
            'validation' => ['uuid'],
        ],
    ],
];
